---
- name: Search for Windows Updates
  hosts: all
  tasks:
    - name: Search for updates only (don’t install yet)
      ansible.windows.win_updates:
        category_names: '*'
        state: searched
        log_path: C:\updates.txt

    - name: Install available updates
      ansible.windows.win_updates:
        category_names: '*'
        reboot: true
